import pygame

WIDTH, HEIGHT = 600, 600
SQUARE_SIZE = WIDTH // 3


BG_COLOR = (255, 87, 51)       
LINE_COLOR = (255, 195, 15)    
CIRCLE_COLOR = LINE_COLOR      
CROSS_COLOR = (255, 255, 255)  
BUTTON_COLOR = LINE_COLOR
BUTTON_HOVER = (255, 215, 40)
TEXT_COLOR = LINE_COLOR

pygame.font.init()
FONT = pygame.font.SysFont(None, 70, bold=True)       
SMALL_FONT = pygame.font.SysFont(None, 45, bold=True) 

LINE_WIDTH = 15
CIRCLE_RADIUS = SQUARE_SIZE // 3
CIRCLE_WIDTH = 18
CROSS_WIDTH = 28
SPACE = SQUARE_SIZE // 4